[piDPC]
parent_directory = /storwis/Labs/cpelbaum/shared/PantherData/20251231_AD155_2/Tomos/
matlab_folder = /home/labs/elbaum/Collaboration
search_pattern = BF-S_Inner1
tilt_step = 2
semi_angle = 1.7
wavelength = 0.0025
bf_disk_location = DF_Outer
matlab_function = panther_xDPC_PK
overwrite = False
